# Generated by Django 5.0.2 on 2024-02-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindex',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='blogindex',
            name='image',
            field=models.ImageField(default=1, upload_to='assets/images'),
            preserve_default=False,
        ),
    ]
