# Generated by Django 5.0.2 on 2024-02-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0002_rename_create_time_blogindex_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindex',
            old_name='created_at',
            new_name='date',
        ),
    ]
