# Generated by Django 5.0.2 on 2024-02-19 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0006_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogIndexb',
        ),
        migrations.DeleteModel(
            name='BlogIndexbb',
        ),
        migrations.DeleteModel(
            name='BlogIndexbbb',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='blogindex',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
