# Generated by Django 5.0.2 on 2024-02-19 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0007_delete_blogindexb_delete_blogindexbb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blogindex',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
