# Generated by Django 5.0.2 on 2024-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0010_alter_blogindex_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindex',
            old_name='body',
            new_name='BodyForText',
        ),
        migrations.RenameField(
            model_name='blogindex',
            old_name='date1',
            new_name='DateTime',
        ),
        migrations.RenameField(
            model_name='blogindex',
            old_name='image',
            new_name='ImageMyProject',
        ),
        migrations.RemoveField(
            model_name='blogindex',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blogindex',
            name='title',
        ),
        migrations.AddField(
            model_name='blogindex',
            name='TitleForProject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
