# Generated by Django 5.0.2 on 2024-02-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0011_rename_body_blogindex_bodyfortext_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndex',
            new_name='MyProjectData',
        ),
    ]
