# Generated by Django 5.0.2 on 2024-02-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0012_rename_blogindex_myprojectdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNameAndFamily', models.CharField(max_length=50)),
                ('Emails', models.CharField(max_length=150)),
                ('BodyText', models.TextField(max_length=500)),
            ],
        ),
    ]
