# Generated by Django 5.0.2 on 2024-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0013_contactbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbox',
            name='BodyText',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactbox',
            name='Emails',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contactbox',
            name='FirstNameAndFamily',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
